---
title: ' Web-based Analysis with R '
author: ' prepared by web-r.org '
date: '`r Sys.time()`'
output: pdf_document
subtitle: '  '
header-includes:
- \usepackage{multirow}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage[table]{xcolor}
- \usepackage{tabularx,booktabs}
- \usepackage{boxedminipage}
- \usepackage{graphicx}
- \usepackage{rotating}
- \usepackage{longtable}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE ,message=FALSE,warning=FALSE,comment=NA,
          fig.width=9,fig.asp=0.618,fig.align='center',out.width='70%')
```
```{r,echo= TRUE ,message=FALSE}
require(moonBook)
require(ztable)
require(rrtable)
require(ggplot2)
options(ztable.type='latex')
```

```{r}
# Preprocessing
require(lavaan)
require(semPlot)
require(semMediation)
require(magrittr)
require(flextable)
model='knowledge =~ general+symptoms+treatmt
empathy =~ cognitiv+emotion+disposit+attitude
intervention =~ classrm+instruct
intervention ~ b*empathy + c*knowledge
empathy ~ a*knowledge
indirect effect:=a*b
total effect:=c+(a*b)'
fit=sem(model,data=ADHD) 
```

### Structural equation modeling 

```{r,echo=TRUE}
model='knowledge =~ general+symptoms+treatmt
empathy =~ cognitiv+emotion+disposit+attitude
intervention =~ classrm+instruct
intervention ~ b*empathy + c*knowledge
empathy ~ a*knowledge
indirect effect:=a*b
total effect:=c+(a*b)'
fit=sem(model,data=ADHD)
 
```



### head(ADHD) 

```{r,echo=FALSE,results='asis'}
df= head(ADHD) 
colnames(df)[colnames(df)=='β']='beta'
ztable(df)
```



### Parameter Estimates Table 

```{r  ,results='asis'}
flextable2ztable(df2flextable(parameterEstimates(fit,standardized=TRUE),vanilla=FALSE))
```



### Cronbach's alpha 

```{r  ,results='asis'}
flextable2ztable(df2flextable(fit2alpha(fit),vanilla=FALSE) %>%
                                 width(width=c(1.5,2,1,1)) %>% align(align='center',part='all'))
```



### Reliability & Validity 

```{r  ,results='asis'}
flextable2ztable(reliabilityTable2(fit,vanilla=FALSE))
```



### Discriminant Validity 

```{r  ,results='asis'}
flextable2ztable(discriminantValidityTable2(fit,vanilla=FALSE))
```



### Correlation among measured variables 

```{r  ,results='asis'}
flextable2ztable(corTable2(fit,vanilla=FALSE))
```



### Correlation Plot 

```{r  }
corPlot(fit) 
```



### Model Fit Table 

```{r  ,results='asis'}
flextable2ztable(df2flextable(modelFitTable(fit),vanilla=FALSE) %>% 
                                 width(width=c(rep(0.5,10),2,1,1)))
```



### Estimated in the Model 

```{r,echo=FALSE,results='asis'}
df= estimatesTable(fit,ci=TRUE) 
colnames(df)[colnames(df)=='β']='beta'
ztable(df)
```



### Mediation Table 

```{r,echo=FALSE,results='asis'}
df= estimatesTable(fit,mediation=TRUE,ci=TRUE) 
colnames(df)[colnames(df)=='β']='beta'
ztable(df)
```



```{r  }
mediationPlot(fit,residuals=FALSE) 
```



